"""empty message

Revision ID: 581f3acab441
Revises: None
Create Date: 2016-05-02 04:10:09.422128

"""

# revision identifiers, used by Alembic.
revision = '581f3acab441'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('audio_features', postgresql.JSON(), nullable=True),
    sa.Column('anger', sa.Integer(), nullable=True),
    sa.Column('contempt', sa.Integer(), nullable=True),
    sa.Column('disgust', sa.Integer(), nullable=True),
    sa.Column('fear', sa.Integer(), nullable=True),
    sa.Column('happiness', sa.Integer(), nullable=True),
    sa.Column('neutral', sa.Integer(), nullable=True),
    sa.Column('sadness', sa.Integer(), nullable=True),
    sa.Column('surprise', sa.Integer(), nullable=True),
    sa.Column('none', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uri')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotions')
    ### end Alembic commands ###
